Update test_secret.yml

diff --git a/.github/workflows/test_secret.yml b/.github/workflows/test_secret.yml
--- a/.github/workflows/test_secret.yml
+++ b/.github/workflows/test_secret.yml
@@ -7,12 +7,60 @@ jobs:
     steps:
       - name: Test secret availability
         env:
-          MY_SECRET: ${{ secrets.SNOWFLAKE_ACCOUNT }}
+          SNOWFLAKE_ACCOUNT_DEV_SECRET: ${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}
+          SNOWFLAKE_USER_DEV_SECRET: ${{ secrets.SNOWFLAKE_USER_DEV }}
+          SNOWFLAKE_PASSWORD_DEV_SECRET: ${{ secrets.SNOWFLAKE_PASSWORD_DEV }}
+          SNOWFLAKE_ROLE_DEV_SECRET: ${{ secrets.SNOWFLAKE_ROLE_DEV }}
+          SNOWFLAKE_DATABASE_DEV_SECRET: ${{ secrets.SNOWFLAKE_DATABASE_DEV }}
+          SNOWFLAKE_SCHEMA_DEV_SECRET: ${{ secrets.SNOWFLAKE_SCHEMA_DEV }}
+          SNOWFLAKE_WAREHOUSE_DEV_SECRET: ${{ secrets.SNOWFLAKE_WAREHOUSE_DEV }}
         run: |
-          if [ -z "$MY_SECRET" ]; then
-            echo "::error::Secret is not set or is empty."
+          if [ -z "$SNOWFLAKE_ACCOUNT_DEV_SECRET" ]; then
+            echo "::error::SNOWFLAKE_ACCOUNT_DEV Secret is not set or is empty."
             exit 1
           else
-            echo "Secret is set and available. Value is redacted."
+            echo "SNOWFLAKE_ACCOUNT_DEV Secret is set and available. Value is redacted."
+            exit 0
+          fi
+          if [ -z "$SNOWFLAKE_USER_DEV_SECRET" ]; then
+            echo "::error::SNOWFLAKE_USER_DEV Secret is not set or is empty."
+            exit 1
+          else
+            echo "SNOWFLAKE_USER_DEV Secret is set and available. Value is redacted."
+            exit 0
+          fi
+          if [ -z "$SNOWFLAKE_PASSWORD_DEV_SECRET" ]; then
+            echo "::error::SNOWFLAKE_PASSWORD_DEV Secret is not set or is empty."
+            exit 1
+          else
+            echo "SNOWFLAKE_PASSWORD_DEV Secret is set and available. Value is redacted."
+            exit 0
+          fi
+          if [ -z "$SNOWFLAKE_ROLE_DEV_SECRET" ]; then
+            echo "::error::SNOWFLAKE_ROLE_DEV Secret is not set or is empty."
+            exit 1
+          else
+            echo "SNOWFLAKE_ROLE_DEV Secret is set and available. Value is redacted."
+            exit 0
+          fi
+          if [ -z "$SNOWFLAKE_DATABASE_DEV_SECRET" ]; then
+            echo "::error::SNOWFLAKE_DATABASE_DEV Secret is not set or is empty."
+            exit 1
+          else
+            echo "SNOWFLAKE_DATABASE_DEV Secret is set and available. Value is redacted."
+            exit 0
+          fi
+          if [ -z "$SNOWFLAKE_SCHEMA_DEV_SECRET" ]; then
+            echo "::error::SNOWFLAKE_SCHEMA_DEV Secret is not set or is empty."
+            exit 1
+          else
+            echo "SNOWFLAKE_SCHEMA_DEV Secret is set and available. Value is redacted."
+            exit 0
+          fi
+          if [ -z "$SNOWFLAKE_WAREHOUSE_DEV_SECRET" ]; then
+            echo "::error::SNOWFLAKE_WAREHOUSE_DEV Secret is not set or is empty."
+            exit 1
+          else
+            echo "SNOWFLAKE_WAREHOUSE_DEV Secret is set and available. Value is redacted."
             exit 0
           fi
